In [1]:
import numpy as np
import pandas as pd
import datetime as dt

In [2]:
#Reading in the springfield data

#Part 1: the main data. Each sheet a different df
SPR2015 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2015',na_values=['      '])
SPR2016 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2016',na_values=['      '])
SPR2017 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2017',na_values=['      '])
SPR2018 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2018',na_values=['      '])
SPR2019 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2019',na_values=['      '])
SPR2020 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2020',na_values=['      '])
SPR2021 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2021',na_values=['      '])
SPR2022 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2022',na_values=['      '])
SPR2023 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2023',na_values=['      '])
SPR2024 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2024',na_values=['      '])
SPR2025 = pd.read_excel("./data/2015-2025 SPD Calls for Service.xlsx",sheet_name='2025',na_values=['      '])

In [3]:
#Part 2: the responding units. Each sheet a different df
UNIT2015 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2015',na_values=['      '])
UNIT2016 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2016',na_values=['      '])
UNIT2017 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2017',na_values=['      '])
UNIT2018 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2018',na_values=['      '])
UNIT2019 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2019',na_values=['      '])
UNIT2020 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2020',na_values=['      '])
UNIT2021 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2021',na_values=['      '])
UNIT2022 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2022',na_values=['      '])
UNIT2023 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2023',na_values=['      '])
UNIT2024 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2024',na_values=['      '])
UNIT2025 = pd.read_excel('./data/2015-2025 SPD Responding Units.xlsx',sheet_name='2025',na_values=['      '])

In [4]:
#Part 3: close codes. Each sheet a different df
CLOSE2015 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2015',na_values='    ')
CLOSE2016 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2016',na_values='    ')
CLOSE2017 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2017',na_values='    ')
CLOSE2018 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2018',na_values='    ')
CLOSE2019 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2019',na_values='    ')
CLOSE2020 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2020',na_values='    ')
CLOSE2021 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2021',na_values='    ')
CLOSE2022 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2022',na_values='    ')
CLOSE2023 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2023',na_values='    ')
CLOSE2024 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2024',na_values='    ')
CLOSE2025 = pd.read_excel('./data/2015-2025 SPD Calls with Close Codes.xlsx',sheet_name='2025',na_values='    ')

In [5]:
#combining into a single SPR welfare data frame [still with no primary units or disposition]
frames = [SPR2015, SPR2016, SPR2017, SPR2018, SPR2019, SPR2020,
          SPR2021, SPR2022, SPR2023, SPR2024, SPR2025]

SPR = pd.concat(frames)
SPR

,Incident Number,Initial Call Type,Final Call Type,Responding Agency,Primary Responding Unit,Call Creation Time,First Dispatched Time,First Arrival Time,Clear Time,Priority,Call Creation Mechanism
0,15000074,ALMAUD,AUDIBLE ALARM,SPD,1S18,2015-01-01 01:16:21,2015-01-01 01:18:28,2015-01-01 01:21:13,2015-01-01 01:32:08,3,PHONE
1,15000083,TRFSTP,DWS,SPD,3D2,2015-01-01 01:22:29,2015-01-01 01:22:29,2015-01-01 01:22:29,2015-01-01 01:34:57,4,SELF
2,15000167,MVAUNK,MOTOR VEH ACC UNKNOWN INJ,SPD,NaN,2015-01-01 03:15:28,NaT,NaT,NaT,3,E911
3,15000216,TRFSTP,DWS,SPD,1S22,2015-01-01 05:27:24,2015-01-01 05:27:24,2015-01-01 05:27:24,2015-01-01 05:38:53,4,SELF
4,15000222,SUSPVE,SUSPICIOUS VEHICLE,SPD,1S11,2015-01-01 05:52:53,2015-01-01 05:53:57,2015-01-01 05:56:21,2015-01-01 06:04:04,3,PHONE
...,...,...,...,...,...,...,...,...,...,...,...
43703,25326475,DISVEH,DISABLED VEHICLE,SPD,1S23,2025-12-30 21:15:10,2025-12-30 21:15:10,2025-12-30 21:15:10,2025-12-30 21:17:20,4,SELF
43704,25326480,TRFSTP,TRAFFIC STOP,SPD,1S23,2025-12-30 21:25:51,2025-12-30 21:25:51,2025-12-30 21:25:51,2025-12-30 21:30:21,6,SELF
43705,25326519,CHKWLF,CHECK WELFARE,SPD,3J81,2025-12-30 22:24:34,2025-12-30 22:25:32,2025-12-30 22:31:12,2025-12-30 22:47:29,7,PHONE
43706,25326528,ALMAUD,AUDIBLE ALARM,SPD,1S21,2025-12-30 22:34:54,2025-12-30 22:41:36,2025-12-30 22:44:28,2025-12-30 22:48:25,3,PHONE
43707,25326529,DSPUT,DISPUTE,SPD,1S13,2025-12-30 22:39:03,2025-12-30 22:42:07,2025-12-30 22:46:51,2025-12-30 22:57:20,3,PHONE

In [6]:
#combining into a single SPR unit data frame
frames = [UNIT2015, UNIT2016, UNIT2017, UNIT2018, UNIT2019, UNIT2020,
          UNIT2021, UNIT2022, UNIT2023, UNIT2024, UNIT2025]
units_all_years = pd.concat(frames)
units_all_years.drop(['Unnamed: 1','call time'],axis=1,inplace=True)
units_all_years

        inci id prime unit units dispatched in order
0      15000004     1S12                      1S12
1      15000013        NaN                       NaN
2      15000022     3S12        4S73  ,3S12  ,3S18
3      15000026     1S12                      1S12
4      15000029     1S18                      1S18
...         ...        ...                       ...
43703  25326541     1S22                      1S22
43704  25326545     1S22                      1S22
43705  25326546     1S11                      1S11
43706  25326550     1S22               1S21  ,1S22
43707  25326551     1S22                      1S22

[567655 rows x 3 columns]

In [7]:
#combining into a single SPR closed_as data frame
frames = [CLOSE2015, CLOSE2016, CLOSE2017, CLOSE2018, CLOSE2019, CLOSE2020,
          CLOSE2021, CLOSE2022, CLOSE2023, CLOSE2024, CLOSE2025]
closed_all_years = pd.concat(frames)
closed_all_years

       Incident Number Close Code
0             15009604        NaN
1             15010887        NaN
2             15019248        NaN
3             15025227        NaN
4             15025271        NaN
...                ...        ...
43703         25308708       XRPT
43704         25310022       XRPT
43705         25317200       XRPT
43706         25320899       XRPT
43707         25325373       XRPT

[567654 rows x 2 columns]

In [8]:
#left join units
intermediate = pd.merge(SPR,units_all_years, left_on='Incident Number', right_on='inci id',how='left')
intermediate.drop('inci id',axis=1,inplace=True)
intermediate

,Incident Number,Initial Call Type,Final Call Type,Responding Agency,Primary Responding Unit,Call Creation Time,First Dispatched Time,First Arrival Time,Clear Time,Priority,Call Creation Mechanism,prime unit,units dispatched in order
0,15000074,ALMAUD,AUDIBLE ALARM,SPD,1S18,2015-01-01 01:16:21,2015-01-01 01:18:28,2015-01-01 01:21:13,2015-01-01 01:32:08,3,PHONE,1S18,"1S18 ,1S21 ,K94"
1,15000083,TRFSTP,DWS,SPD,3D2,2015-01-01 01:22:29,2015-01-01 01:22:29,2015-01-01 01:22:29,2015-01-01 01:34:57,4,SELF,3D2,3D2
2,15000167,MVAUNK,MOTOR VEH ACC UNKNOWN INJ,SPD,NaN,2015-01-01 03:15:28,NaT,NaT,NaT,3,E911,NaN,NaN
3,15000216,TRFSTP,DWS,SPD,1S22,2015-01-01 05:27:24,2015-01-01 05:27:24,2015-01-01 05:27:24,2015-01-01 05:38:53,4,SELF,1S22,1S22
4,15000222,SUSPVE,SUSPICIOUS VEHICLE,SPD,1S11,2015-01-01 05:52:53,2015-01-01 05:53:57,2015-01-01 05:56:21,2015-01-01 06:04:04,3,PHONE,1S11,"1S11 ,1S12"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
567650,25326475,DISVEH,DISABLED VEHICLE,SPD,1S23,2025-12-30 21:15:10,2025-12-30 21:15:10,2025-12-30 21:15:10,2025-12-30 21:17:20,4,SELF,1S23,1S23
567651,25326480,TRFSTP,TRAFFIC STOP,SPD,1S23,2025-12-30 21:25:51,2025-12-30 21:25:51,2025-12-30 21:25:51,2025-12-30 21:30:21,6,SELF,1S23,1S23
567652,25326519,CHKWLF,CHECK WELFARE,SPD,3J81,2025-12-30 22:24:34,2025-12-30 22:25:32,2025-12-30 22:31:12,2025-12-30 22:47:29,7,PHONE,3J81,3J81
567653,25326528,ALMAUD,AUDIBLE ALARM,SPD,1S21,2025-12-30 22:34:54,2025-12-30 22:41:36,2025-12-30 22:44:28,2025-12-30 22:48:25,3,PHONE,1S21,"1S21 ,1S22"
567654,25326529,DSPUT,DISPUTE,SPD,1S13,2025-12-30 22:39:03,2025-12-30 22:42:07,2025-12-30 22:46:51,2025-12-30 22:57:20,3,PHONE,1S13,"1S11 ,1S13"

In [9]:
#left join closed codes
SPR = pd.merge(intermediate,closed_all_years, on='Incident Number',how='left')
SPR

,Incident Number,Initial Call Type,Final Call Type,Responding Agency,Primary Responding Unit,Call Creation Time,First Dispatched Time,First Arrival Time,Clear Time,Priority,Call Creation Mechanism,prime unit,units dispatched in order,Close Code
0,15000074,ALMAUD,AUDIBLE ALARM,SPD,1S18,2015-01-01 01:16:21,2015-01-01 01:18:28,2015-01-01 01:21:13,2015-01-01 01:32:08,3,PHONE,1S18,"1S18 ,1S21 ,K94",BLDS
1,15000083,TRFSTP,DWS,SPD,3D2,2015-01-01 01:22:29,2015-01-01 01:22:29,2015-01-01 01:22:29,2015-01-01 01:34:57,4,SELF,3D2,3D2,UTC
2,15000167,MVAUNK,MOTOR VEH ACC UNKNOWN INJ,SPD,NaN,2015-01-01 03:15:28,NaT,NaT,NaT,3,E911,NaN,NaN,DUP
3,15000216,TRFSTP,DWS,SPD,1S22,2015-01-01 05:27:24,2015-01-01 05:27:24,2015-01-01 05:27:24,2015-01-01 05:38:53,4,SELF,1S22,1S22,UTC
4,15000222,SUSPVE,SUSPICIOUS VEHICLE,SPD,1S11,2015-01-01 05:52:53,2015-01-01 05:53:57,2015-01-01 05:56:21,2015-01-01 06:04:04,3,PHONE,1S11,"1S11 ,1S12",INFO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567650,25326475,DISVEH,DISABLED VEHICLE,SPD,1S23,2025-12-30 21:15:10,2025-12-30 21:15:10,2025-12-30 21:15:10,2025-12-30 21:17:20,4,SELF,1S23,1S23,RSLV
567651,25326480,TRFSTP,TRAFFIC STOP,SPD,1S23,2025-12-30 21:25:51,2025-12-30 21:25:51,2025-12-30 21:25:51,2025-12-30 21:30:21,6,SELF,1S23,1S23,WARN
567652,25326519,CHKWLF,CHECK WELFARE,SPD,3J81,2025-12-30 22:24:34,2025-12-30 22:25:32,2025-12-30 22:31:12,2025-12-30 22:47:29,7,PHONE,3J81,3J81,ASST
567653,25326528,ALMAUD,AUDIBLE ALARM,SPD,1S21,2025-12-30 22:34:54,2025-12-30 22:41:36,2025-12-30 22:44:28,2025-12-30 22:48:25,3,PHONE,1S21,"1S21 ,1S22",FALS
567654,25326529,DSPUT,DISPUTE,SPD,1S13,2025-12-30 22:39:03,2025-12-30 22:42:07,2025-12-30 22:46:51,2025-12-30 22:57:20,3,PHONE,1S13,"1S11 ,1S13",ASST

In [10]:
#Make new columns for month and year, for later grouping
SPR['month'] = SPR['Call Creation Time'].dt.month
SPR['year'] = SPR['Call Creation Time'].dt.year

In [11]:
#Strip whitespace
SPR['Primary Responding Unit'] = SPR['Primary Responding Unit'].str.strip()
SPR['prime unit'] = SPR['prime unit'].str.strip()
SPR['units dispatched in order'] = SPR['units dispatched in order'].str.strip()

In [12]:
#getting the count of units dispatched

#first, count number of units
unit_count = SPR['units dispatched in order'].str.count(",") + 1


#second, make new column
SPR['units dispatched'] = unit_count

#third, convert NA values to zeros
SPR['units dispatched'] = SPR['units dispatched'].fillna(0)

In [13]:
#dropping rows where the primeunit is a null value and more than 0 units were dispatched
SPR = SPR[(SPR['Primary Responding Unit'].notna()) | (SPR['units dispatched'] == 0.)]
SPR

,Incident Number,Initial Call Type,Final Call Type,Responding Agency,Primary Responding Unit,Call Creation Time,First Dispatched Time,First Arrival Time,Clear Time,Priority,Call Creation Mechanism,prime unit,units dispatched in order,Close Code,month,year,units dispatched
0,15000074,ALMAUD,AUDIBLE ALARM,SPD,1S18,2015-01-01 01:16:21,2015-01-01 01:18:28,2015-01-01 01:21:13,2015-01-01 01:32:08,3,PHONE,1S18,"1S18 ,1S21 ,K94",BLDS,1,2015,3.0
1,15000083,TRFSTP,DWS,SPD,3D2,2015-01-01 01:22:29,2015-01-01 01:22:29,2015-01-01 01:22:29,2015-01-01 01:34:57,4,SELF,3D2,3D2,UTC,1,2015,1.0
2,15000167,MVAUNK,MOTOR VEH ACC UNKNOWN INJ,SPD,NaN,2015-01-01 03:15:28,NaT,NaT,NaT,3,E911,NaN,NaN,DUP,1,2015,0.0
3,15000216,TRFSTP,DWS,SPD,1S22,2015-01-01 05:27:24,2015-01-01 05:27:24,2015-01-01 05:27:24,2015-01-01 05:38:53,4,SELF,1S22,1S22,UTC,1,2015,1.0
4,15000222,SUSPVE,SUSPICIOUS VEHICLE,SPD,1S11,2015-01-01 05:52:53,2015-01-01 05:53:57,2015-01-01 05:56:21,2015-01-01 06:04:04,3,PHONE,1S11,"1S11 ,1S12",INFO,1,2015,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567650,25326475,DISVEH,DISABLED VEHICLE,SPD,1S23,2025-12-30 21:15:10,2025-12-30 21:15:10,2025-12-30 21:15:10,2025-12-30 21:17:20,4,SELF,1S23,1S23,RSLV,12,2025,1.0
567651,25326480,TRFSTP,TRAFFIC STOP,SPD,1S23,2025-12-30 21:25:51,2025-12-30 21:25:51,2025-12-30 21:25:51,2025-12-30 21:30:21,6,SELF,1S23,1S23,WARN,12,2025,1.0
567652,25326519,CHKWLF,CHECK WELFARE,SPD,3J81,2025-12-30 22:24:34,2025-12-30 22:25:32,2025-12-30 22:31:12,2025-12-30 22:47:29,7,PHONE,3J81,3J81,ASST,12,2025,1.0
567653,25326528,ALMAUD,AUDIBLE ALARM,SPD,1S21,2025-12-30 22:34:54,2025-12-30 22:41:36,2025-12-30 22:44:28,2025-12-30 22:48:25,3,PHONE,1S21,"1S21 ,1S22",FALS,12,2025,2.0
567654,25326529,DSPUT,DISPUTE,SPD,1S13,2025-12-30 22:39:03,2025-12-30 22:42:07,2025-12-30 22:46:51,2025-12-30 22:57:20,3,PHONE,1S13,"1S11 ,1S13",ASST,12,2025,2.0

In [14]:
#Adding a column saying whether cahoots, spd, or neither answered the call

SPR["Institution"] = np.where(    
    SPR["Primary Responding Unit"].str.contains("J|CAH", na=False),    
    "CAHOOTS",    
    np.where(        
        SPR["Primary Responding Unit"].isna(),        
        "Neither",        
        "SPD"    
    )
)

/var/folders/0y/gklqyv_101130y1ly46wc5wm0000gn/T/ipykernel_83409/3035309939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  SPR["Institution"] = np.where(

In [15]:
#check for duplicate rows
sum(SPR.duplicated())

0

In [16]:
SPR

,Incident Number,Initial Call Type,Final Call Type,Responding Agency,Primary Responding Unit,Call Creation Time,First Dispatched Time,First Arrival Time,Clear Time,Priority,Call Creation Mechanism,prime unit,units dispatched in order,Close Code,month,year,units dispatched,Institution
0,15000074,ALMAUD,AUDIBLE ALARM,SPD,1S18,2015-01-01 01:16:21,2015-01-01 01:18:28,2015-01-01 01:21:13,2015-01-01 01:32:08,3,PHONE,1S18,"1S18 ,1S21 ,K94",BLDS,1,2015,3.0,SPD
1,15000083,TRFSTP,DWS,SPD,3D2,2015-01-01 01:22:29,2015-01-01 01:22:29,2015-01-01 01:22:29,2015-01-01 01:34:57,4,SELF,3D2,3D2,UTC,1,2015,1.0,SPD
2,15000167,MVAUNK,MOTOR VEH ACC UNKNOWN INJ,SPD,NaN,2015-01-01 03:15:28,NaT,NaT,NaT,3,E911,NaN,NaN,DUP,1,2015,0.0,Neither
3,15000216,TRFSTP,DWS,SPD,1S22,2015-01-01 05:27:24,2015-01-01 05:27:24,2015-01-01 05:27:24,2015-01-01 05:38:53,4,SELF,1S22,1S22,UTC,1,2015,1.0,SPD
4,15000222,SUSPVE,SUSPICIOUS VEHICLE,SPD,1S11,2015-01-01 05:52:53,2015-01-01 05:53:57,2015-01-01 05:56:21,2015-01-01 06:04:04,3,PHONE,1S11,"1S11 ,1S12",INFO,1,2015,2.0,SPD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567650,25326475,DISVEH,DISABLED VEHICLE,SPD,1S23,2025-12-30 21:15:10,2025-12-30 21:15:10,2025-12-30 21:15:10,2025-12-30 21:17:20,4,SELF,1S23,1S23,RSLV,12,2025,1.0,SPD
567651,25326480,TRFSTP,TRAFFIC STOP,SPD,1S23,2025-12-30 21:25:51,2025-12-30 21:25:51,2025-12-30 21:25:51,2025-12-30 21:30:21,6,SELF,1S23,1S23,WARN,12,2025,1.0,SPD
567652,25326519,CHKWLF,CHECK WELFARE,SPD,3J81,2025-12-30 22:24:34,2025-12-30 22:25:32,2025-12-30 22:31:12,2025-12-30 22:47:29,7,PHONE,3J81,3J81,ASST,12,2025,1.0,CAHOOTS
567653,25326528,ALMAUD,AUDIBLE ALARM,SPD,1S21,2025-12-30 22:34:54,2025-12-30 22:41:36,2025-12-30 22:44:28,2025-12-30 22:48:25,3,PHONE,1S21,"1S21 ,1S22",FALS,12,2025,2.0,SPD
567654,25326529,DSPUT,DISPUTE,SPD,1S13,2025-12-30 22:39:03,2025-12-30 22:42:07,2025-12-30 22:46:51,2025-12-30 22:57:20,3,PHONE,1S13,"1S11 ,1S13",ASST,12,2025,2.0,SPD

In [17]:
#export of cleaned Springfield data
SPR.to_csv("./data/SPR_cleaned.csv")